//! 5-language emit — `GraphSpec` → Rust / Kotlin / Python / C++ / Protobuf source
//! strings. Deterministic byte-identical output for identical input.
//!
//! Prototype `bench/codegen-prototype/src/entity_indexer.rs::emit_*` production
//! previous. Rust authoritative, others reference (cross-language conformance source).

use crate::schema::{EntityDef, FieldType, GraphSpec, Persistence, RelationDef};

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct EmittedMultiLang {
    pub rust: String,
    pub kotlin: String,
    pub python: String,
    pub cpp: String,
    pub protobuf: String,
}

pub fn emit_all_languages(spec: &GraphSpec) -> EmittedMultiLang {
    EmittedMultiLang {
        rust: emit_rust(spec),
        kotlin: emit_kotlin(spec),
        python: emit_python(spec),
        cpp: emit_cpp(spec),
        protobuf: emit_protobuf(spec),
    }
}

// ────────────────────────────────────────────────────────────────────────────
// Rust emit (authoritative — production target compile path).
// ────────────────────────────────────────────────────────────────────────────

pub fn emit_rust(spec: &GraphSpec) -> String {
    let mut out = String::new();
    out.push_str("// Auto-generated by mnemosyne-facts (DESIGN §39 entity-indexer).\n");
    out.push_str("// Phase -1A stage 2C carry — 24 B BE composite key.\n\n");
    out.push_str("use byteorder::{BigEndian, ByteOrder};\n\n");
    out.push_str("pub const KEY_LEN: usize = 24;\n\n");

    for entity in &spec.entities {
        emit_rust_entity(&mut out, entity);
    }
    for relation in &spec.relations {
        emit_rust_relation(&mut out, relation);
    }
    out
}

fn emit_rust_entity(out: &mut String, entity: &EntityDef) {
    out.push_str(persistence_marker_rust(entity.persistence));
    out.push('\n');
    out.push_str("#[derive(Debug, Clone)]\n");
    out.push_str(&format!("pub struct {} {{\n", entity.name));
    out.push_str(&format!(
        " pub {}: u64, // composite key — 8 B BE prefix\n",
        entity.key.branch_field
    ));
    out.push_str(&format!(
        " pub {}: u64, // composite key — 8 B BE entity_id\n",
        entity.key.entity_field
    ));
    out.push_str(&format!(
        " pub {}: u64, // composite key — 8 B BE valid_from\n",
        entity.key.valid_from_field
    ));
    for field in &entity.fields {
        out.push_str(&format!(
            " pub {}: {},\n",
            field.name,
            rust_type_for(&field.ty, field.nullable)
        ));
    }
    out.push_str("}\n");
    out.push_str(&format!("impl {} {{\n", entity.name));
    out.push_str(" pub fn encode_key(&self) -> [u8; KEY_LEN] {\n");
    out.push_str(" let mut buf = [0u8; KEY_LEN];\n");
    out.push_str(&format!(
        " BigEndian::write_u64(&mut buf[0..8], self.{});\n",
        entity.key.branch_field
    ));
    out.push_str(&format!(
        " BigEndian::write_u64(&mut buf[8..16], self.{});\n",
        entity.key.entity_field
    ));
    out.push_str(&format!(
        " BigEndian::write_u64(&mut buf[16..24], self.{});\n",
        entity.key.valid_from_field
    ));
    out.push_str(" buf\n");
    out.push_str(" }\n");
    out.push_str("}\n\n");
}

fn emit_rust_relation(out: &mut String, relation: &RelationDef) {
    out.push_str(persistence_marker_rust(relation.persistence));
    out.push('\n');
    out.push_str("#[derive(Debug, Clone)]\n");
    out.push_str(&format!("pub struct {} {{\n", relation.name));
    out.push_str(&format!(
        " pub from: u64, // {} entity_id\n",
        relation.from_entity
    ));
    out.push_str(&format!(
        " pub to: u64, // {} entity_id\n",
        relation.to_entity
    ));
    for field in &relation.fields {
        out.push_str(&format!(
            " pub {}: {},\n",
            field.name,
            rust_type_for(&field.ty, field.nullable)
        ));
    }
    out.push_str("}\n\n");
}

fn persistence_marker_rust(p: Persistence) -> &'static str {
    match p {
        Persistence::Persistent => "// @persistent — explicit CF",
        Persistence::Derived => "// @derived — derived CF",
    }
}

fn rust_type_for(ty: &FieldType, nullable: bool) -> String {
    let base = match ty {
        FieldType::U64BigEndian => "u64".to_string(),
        FieldType::String => "String".to_string(),
        FieldType::Bytes => "Vec<u8>".to_string(),
        FieldType::EntityRef { target } => format!("/* ref: {target} */ u64"),
        FieldType::NormalizedAssetRefs => {
            "Vec<u64> // row-per-(asset, fact) normalized".to_string()
        }
        FieldType::RowPerEncounter => "Vec<u64> // row-per-encounter (§44)".to_string(),
    };
    if nullable {
        format!("Option<{base}>")
    } else {
        base
    }
}

// ────────────────────────────────────────────────────────────────────────────
// Kotlin emit (reference — Studio data class).
// ────────────────────────────────────────────────────────────────────────────

pub fn emit_kotlin(spec: &GraphSpec) -> String {
    let mut out = String::new();
    out.push_str("// Auto-generated by mnemosyne-facts (DESIGN §39 entity-indexer Kotlin).\n");
    out.push_str("// Reference emit — Studio data class shape.\n\n");
    out.push_str("package mnemosyne.generated\n\n");
    out.push_str("const val KEY_LEN: Int = 24\n\n");

    for entity in &spec.entities {
        out.push_str(persistence_marker_kotlin(entity.persistence));
        out.push('\n');
        out.push_str(&format!("data class {}(\n", entity.name));
        out.push_str(&format!(
            " val {}: ULong, // composite key — 8 B BE prefix\n",
            entity.key.branch_field
        ));
        out.push_str(&format!(
            " val {}: ULong, // composite key — 8 B BE entity_id\n",
            entity.key.entity_field
        ));
        out.push_str(&format!(
            " val {}: ULong, // composite key — 8 B BE valid_from\n",
            entity.key.valid_from_field
        ));
        for field in &entity.fields {
            out.push_str(&format!(
                " val {}: {},\n",
                field.name,
                kotlin_type_for(&field.ty, field.nullable)
            ));
        }
        out.push_str(")\n\n");
    }
    for relation in &spec.relations {
        out.push_str(persistence_marker_kotlin(relation.persistence));
        out.push('\n');
        out.push_str(&format!("data class {}(\n", relation.name));
        out.push_str(&format!(
            " val from: ULong, // {} entity_id\n",
            relation.from_entity
        ));
        out.push_str(&format!(
            " val to: ULong, // {} entity_id\n",
            relation.to_entity
        ));
        for field in &relation.fields {
            out.push_str(&format!(
                " val {}: {},\n",
                field.name,
                kotlin_type_for(&field.ty, field.nullable)
            ));
        }
        out.push_str(")\n\n");
    }
    out
}

fn persistence_marker_kotlin(p: Persistence) -> &'static str {
    persistence_marker_rust(p) // identical comment shape
}

fn kotlin_type_for(ty: &FieldType, nullable: bool) -> String {
    let base = match ty {
        FieldType::U64BigEndian => "ULong".to_string(),
        FieldType::String => "String".to_string(),
        FieldType::Bytes => "ByteArray".to_string(),
        FieldType::EntityRef { target } => format!("ULong /* ref: {target} */"),
        FieldType::NormalizedAssetRefs => {
            "List<ULong> /* row-per-(asset, fact) normalized */".to_string()
        }
        FieldType::RowPerEncounter => "List<ULong> /* row-per-encounter (§44) */".to_string(),
    };
    if nullable {
        format!("{base}?")
    } else {
        base
    }
}

// ────────────────────────────────────────────────────────────────────────────
// Python emit (reference — CLI dataclass).
// ────────────────────────────────────────────────────────────────────────────

pub fn emit_python(spec: &GraphSpec) -> String {
    let mut out = String::new();
    out.push_str("# Auto-generated by mnemosyne-facts (DESIGN §39 entity-indexer Python).\n");
    out.push_str("# Reference emit — CLI dataclass shape.\n\n");
    out.push_str("from dataclasses import dataclass\n");
    out.push_str("from typing import Optional, List\n\n");
    out.push_str("KEY_LEN: int = 24\n\n");

    for entity in &spec.entities {
        out.push_str(persistence_marker_python(entity.persistence));
        out.push('\n');
        out.push_str("@dataclass\n");
        out.push_str(&format!("class {}:\n", entity.name));
        out.push_str(&format!(
            " {}: int # composite key — 8 B BE prefix\n",
            entity.key.branch_field
        ));
        out.push_str(&format!(
            " {}: int # composite key — 8 B BE entity_id\n",
            entity.key.entity_field
        ));
        out.push_str(&format!(
            " {}: int # composite key — 8 B BE valid_from\n",
            entity.key.valid_from_field
        ));
        for field in &entity.fields {
            out.push_str(&format!(
                " {}: {}\n",
                field.name,
                python_type_for(&field.ty, field.nullable)
            ));
        }
        out.push('\n');
    }
    for relation in &spec.relations {
        out.push_str(persistence_marker_python(relation.persistence));
        out.push('\n');
        out.push_str("@dataclass\n");
        out.push_str(&format!("class {}:\n", relation.name));
        out.push_str(&format!(
            " from_: int # {} entity_id\n",
            relation.from_entity
        ));
        out.push_str(&format!(" to: int # {} entity_id\n", relation.to_entity));
        for field in &relation.fields {
            out.push_str(&format!(
                " {}: {}\n",
                field.name,
                python_type_for(&field.ty, field.nullable)
            ));
        }
        out.push('\n');
    }
    out
}

fn persistence_marker_python(p: Persistence) -> &'static str {
    match p {
        Persistence::Persistent => "# @persistent — explicit CF",
        Persistence::Derived => "# @derived — derived CF",
    }
}

fn python_type_for(ty: &FieldType, nullable: bool) -> String {
    let base = match ty {
        FieldType::U64BigEndian => "int".to_string(),
        FieldType::String => "str".to_string(),
        FieldType::Bytes => "bytes".to_string(),
        FieldType::EntityRef { target } => format!("int # ref: {target}"),
        FieldType::NormalizedAssetRefs => {
            "List[int] # row-per-(asset, fact) normalized".to_string()
        }
        FieldType::RowPerEncounter => "List[int] # row-per-encounter (§44)".to_string(),
    };
    if nullable {
        format!("Optional[{base}]")
    } else {
        base
    }
}

// ────────────────────────────────────────────────────────────────────────────
// C++ emit (reference — runtime SDK header).
// ────────────────────────────────────────────────────────────────────────────

pub fn emit_cpp(spec: &GraphSpec) -> String {
    let mut out = String::new();
    out.push_str("// Auto-generated by mnemosyne-facts (DESIGN §39 entity-indexer C++).\n");
    out.push_str("// Reference emit — runtime SDK POD struct shape.\n\n");
    out.push_str("#pragma once\n");
    out.push_str(
        "#include <cstdint>\n#include <string>\n#include <vector>\n#include <optional>\n\n",
    );
    out.push_str("namespace mnemosyne::generated {\n\n");
    out.push_str("constexpr std::size_t KEY_LEN = 24;\n\n");

    for entity in &spec.entities {
        out.push_str(persistence_marker_rust(entity.persistence));
        out.push('\n');
        out.push_str(&format!("struct {} {{\n", entity.name));
        out.push_str(&format!(
            " uint64_t {}; // composite key — 8 B BE prefix\n",
            entity.key.branch_field
        ));
        out.push_str(&format!(
            " uint64_t {}; // composite key — 8 B BE entity_id\n",
            entity.key.entity_field
        ));
        out.push_str(&format!(
            " uint64_t {}; // composite key — 8 B BE valid_from\n",
            entity.key.valid_from_field
        ));
        for field in &entity.fields {
            out.push_str(&format!(
                " {} {};\n",
                cpp_type_for(&field.ty, field.nullable),
                field.name
            ));
        }
        out.push_str("};\n\n");
    }
    for relation in &spec.relations {
        out.push_str(persistence_marker_rust(relation.persistence));
        out.push('\n');
        out.push_str(&format!("struct {} {{\n", relation.name));
        out.push_str(&format!(
            " uint64_t from; // {} entity_id\n",
            relation.from_entity
        ));
        out.push_str(&format!(
            " uint64_t to; // {} entity_id\n",
            relation.to_entity
        ));
        for field in &relation.fields {
            out.push_str(&format!(
                " {} {};\n",
                cpp_type_for(&field.ty, field.nullable),
                field.name
            ));
        }
        out.push_str("};\n\n");
    }
    out.push_str("} // namespace mnemosyne::generated\n");
    out
}

fn cpp_type_for(ty: &FieldType, nullable: bool) -> String {
    let base = match ty {
        FieldType::U64BigEndian => "uint64_t".to_string(),
        FieldType::String => "std::string".to_string(),
        FieldType::Bytes => "std::vector<uint8_t>".to_string(),
        FieldType::EntityRef { target } => format!("uint64_t /* ref: {target} */"),
        FieldType::NormalizedAssetRefs => {
            "std::vector<uint64_t> /* row-per-(asset, fact) normalized */".to_string()
        }
        FieldType::RowPerEncounter => {
            "std::vector<uint64_t> /* row-per-encounter (§44) */".to_string()
        }
    };
    if nullable {
        format!("std::optional<{base}>")
    } else {
        base
    }
}

// ────────────────────────────────────────────────────────────────────────────
// Protobuf emit (reference — wire format spec).
// ────────────────────────────────────────────────────────────────────────────

pub fn emit_protobuf(spec: &GraphSpec) -> String {
    let mut out = String::new();
    out.push_str("// Auto-generated by mnemosyne-facts (DESIGN §39 entity-indexer protobuf).\n");
    out.push_str("// Reference emit — wire format spec.\n\n");
    out.push_str("syntax = \"proto3\";\n\n");
    out.push_str("package mnemosyne.generated;\n\n");
    out.push_str("// KEY_LEN = 24 (composite key wire size)\n\n");

    for entity in &spec.entities {
        out.push_str(persistence_marker_rust(entity.persistence));
        out.push('\n');
        out.push_str(&format!("message {} {{\n", entity.name));
        let mut idx = 1u32;
        out.push_str(&format!(
            " uint64 {} = {}; // composite key — 8 B BE prefix\n",
            entity.key.branch_field, idx
        ));
        idx += 1;
        out.push_str(&format!(
            " uint64 {} = {}; // composite key — 8 B BE entity_id\n",
            entity.key.entity_field, idx
        ));
        idx += 1;
        out.push_str(&format!(
            " uint64 {} = {}; // composite key — 8 B BE valid_from\n",
            entity.key.valid_from_field, idx
        ));
        idx += 1;
        for field in &entity.fields {
            out.push_str(&format!(
                " {} {} = {};\n",
                proto_type_prefix(&field.ty, field.nullable),
                field.name,
                idx
            ));
            idx += 1;
        }
        out.push_str("}\n\n");
    }
    for relation in &spec.relations {
        out.push_str(persistence_marker_rust(relation.persistence));
        out.push('\n');
        out.push_str(&format!("message {} {{\n", relation.name));
        let mut idx = 1u32;
        out.push_str(&format!(
            " uint64 from = {}; // {} entity_id\n",
            idx, relation.from_entity
        ));
        idx += 1;
        out.push_str(&format!(
            " uint64 to = {}; // {} entity_id\n",
            idx, relation.to_entity
        ));
        idx += 1;
        for field in &relation.fields {
            out.push_str(&format!(
                " {} {} = {};\n",
                proto_type_prefix(&field.ty, field.nullable),
                field.name,
                idx
            ));
            idx += 1;
        }
        out.push_str("}\n\n");
    }
    out
}

fn proto_type_prefix(ty: &FieldType, nullable: bool) -> String {
    let base = match ty {
        FieldType::U64BigEndian => "uint64",
        FieldType::String => "string",
        FieldType::Bytes => "bytes",
        FieldType::EntityRef { .. } => "uint64",
        FieldType::NormalizedAssetRefs => "repeated uint64",
        FieldType::RowPerEncounter => "repeated uint64",
    };
    if nullable && !base.starts_with("repeated") {
        format!("optional {base}")
    } else {
        base.to_string()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::canonical::{canonical_identifier_set, jaccard_inclusion, sha256_hex};
    use crate::fixture::design_doc_schema_fixture;

    #[test]
    fn five_languages_deterministic() {
        let spec = design_doc_schema_fixture();
        let a = emit_all_languages(&spec);
        let b = emit_all_languages(&spec);
        assert_eq!(a, b);
    }

    #[test]
    fn five_languages_distinct_sha256() {
        let spec = design_doc_schema_fixture();
        let m = emit_all_languages(&spec);
        let mut seen = std::collections::BTreeSet::new();
        for s in [&m.rust, &m.kotlin, &m.python, &m.cpp, &m.protobuf] {
            let h = sha256_hex(s);
            assert_eq!(h.len(), 64);
            assert!(seen.insert(h));
        }
        assert_eq!(seen.len(), 5);
    }

    #[test]
    fn cross_language_jaccard_one() {
        let spec = design_doc_schema_fixture();
        let canonical = canonical_identifier_set(&spec);
        let m = emit_all_languages(&spec);
        for (lang, text) in [
            ("rust", &m.rust),
            ("kotlin", &m.kotlin),
            ("python", &m.python),
            ("cpp", &m.cpp),
            ("protobuf", &m.protobuf),
        ] {
            let j = jaccard_inclusion(text, &canonical);
            assert!((j - 1.0).abs() < f64::EPSILON, "{lang}: {j}");
        }
    }

    #[test]
    fn rust_emit_contains_all_entities_and_key_codec() {
        let spec = design_doc_schema_fixture();
        let r = emit_rust(&spec);
        for n in ["Section", "ChangelogEntry", "FrozenList", "CrossRef"] {
            assert!(r.contains(&format!("pub struct {}", n)));
        }
        assert!(r.contains("pub const KEY_LEN: usize = 24;"));
        assert!(r.contains("BigEndian::write_u64(&mut buf[0..8]"));
        assert!(r.contains("BigEndian::write_u64(&mut buf[16..24]"));
    }

    #[test]
    fn protobuf_field_indices_start_at_one_and_increment() {
        let spec = design_doc_schema_fixture();
        let p = emit_protobuf(&spec);
        assert!(p.contains("uint64 branch_id = 1;"));
        assert!(p.contains("uint64 entity_id = 2;"));
        assert!(p.contains("uint64 valid_from = 3;"));
    }

    #[test]
    fn entity_ref_target_preserved_across_languages() {
        let spec = design_doc_schema_fixture();
        let m = emit_all_languages(&spec);
        // FrozenList.owner_section is EntityRef { target: "Section" }.
        assert!(m.rust.contains("/* ref: Section */"));
        assert!(m.kotlin.contains("/* ref: Section */"));
        assert!(m.python.contains("# ref: Section"));
        assert!(m.cpp.contains("/* ref: Section */"));
    }
}
