// The code generator: ProjectionParts -> Rust source (Round 770).
//
// `include!`d by this crate's own `build.rs` as well as compiled into the lib,
// so the generator that CI compiles is the same text the build script runs —
// there is no second copy to drift. That is also why this file carries `//`
// comments rather than `//!` module docs: an inner doc comment cannot appear
// where an `include!` splices it.

use std::fmt::Write as _;

use mnemosyne_engine::{
    CastPart, ContentAnchor, DoorPart, ForkPart, Interactivity, LinePart, Locator, ProjectionParts,
    Rung,
};

/// The item the generated source defines.
const FN_NAME: &str = "playable_projection";

/// Render parts as Rust source. Deterministic — [`ProjectionParts`] is emitted in
/// sorted key order (R769), so an unchanged store yields a byte-identical file
/// and a no-op rebuild churns nothing downstream.
#[must_use]
pub fn render(parts: &ProjectionParts) -> String {
    let mut out = String::new();
    out.push_str("// @generated by mnemosyne-engine-build. Do not edit.\n");
    out.push_str("// Baked from the store at build time; regenerated whenever the store moves.\n");
    let _ = writeln!(
        out,
        "pub fn {FN_NAME}() -> ::mnemosyne_engine::PlayableProjection {{"
    );
    out.push_str("    ::mnemosyne_engine::PlayableProjection::from_parts(\n");
    out.push_str("        ::mnemosyne_engine::ProjectionParts {\n");
    let _ = writeln!(out, "            telling: {},", string(&parts.telling));
    let _ = writeln!(
        out,
        "            by_world: {},",
        vec_of(&parts.by_world, |(world, sections)| {
            format!(
                "({}, {})",
                string(world),
                vec_of(sections, |(section, lines)| format!(
                    "({}, {})",
                    string(section),
                    vec_of(lines, line)
                ))
            )
        })
    );
    let _ = writeln!(
        out,
        "            walks: {},",
        vec_of(&parts.walks, |(world, walk)| format!(
            "({}, {})",
            string(world),
            strings(walk)
        ))
    );
    let _ = writeln!(
        out,
        "            titles: {},",
        vec_of(&parts.titles, |(section, title)| format!(
            "({}, {})",
            string(section),
            string(title)
        ))
    );
    let _ = writeln!(
        out,
        "            cast: {},",
        vec_of(&parts.cast, |(section, members)| format!(
            "({}, {})",
            string(section),
            vec_of(members, cast)
        ))
    );
    let _ = writeln!(out, "            forks: {},", vec_of(&parts.forks, fork));
    let _ = writeln!(
        out,
        "            divergent_endings: {},",
        strings(&parts.divergent_endings)
    );
    let _ = writeln!(
        out,
        "            interactivity: {},",
        interactivity(&parts.interactivity)
    );
    let _ = writeln!(
        out,
        "            choice_entity_refs: {},",
        vec_of(&parts.choice_entity_refs, |r| format!(
            "::mnemosyne_engine::ChoiceEntityRef {{ section: {}, entity: {}, choice: {} }}",
            string(&r.section),
            string(&r.entity),
            string(&r.choice)
        ))
    );
    let _ = writeln!(
        out,
        "            ask_doors: {},",
        vec_of(&parts.ask_doors, |(section, doors)| format!(
            "({}, {})",
            string(section),
            vec_of(doors, door)
        ))
    );
    out.push_str("        },\n    )\n}\n");
    out
}

/// A Rust string literal for `s`. `{:?}` on a `&str` is exactly the escaping
/// rules of a Rust literal, so this is a correct quoter rather than an
/// approximate one — a claim worth stating because the values being quoted are
/// authored prose full of quotes, newlines and non-ASCII.
fn string(s: &str) -> String {
    format!("{s:?}.to_string()")
}

fn strings(items: &[String]) -> String {
    vec_of(items, |s| string(s))
}

fn vec_of<T>(items: &[T], each: impl Fn(&T) -> String) -> String {
    if items.is_empty() {
        return "::std::vec::Vec::new()".to_string();
    }
    let body: Vec<String> = items.iter().map(each).collect();
    format!("vec![{}]", body.join(", "))
}

fn option(inner: Option<String>) -> String {
    inner.map_or_else(|| "None".to_string(), |value| format!("Some({value})"))
}

fn line(part: &LinePart) -> String {
    format!(
        "::mnemosyne_engine::LinePart {{ fact_id: {}, text: {}, mode: {}, frame: {}, \
         entities: {}, carrier: {}, typed_predicate: {}, quote: {}, count: {} }}",
        string(&part.fact_id),
        string(&part.text),
        disclosure_mode(part.mode),
        string(&part.frame),
        strings(&part.entities),
        option(part.carrier.as_deref().map(string)),
        option(part.typed_predicate.as_deref().map(string)),
        option(part.quote.as_deref().map(string)),
        option(part.count.map(|c| format!("{c}i64"))),
    )
}

fn cast(part: &CastPart) -> String {
    format!(
        "::mnemosyne_engine::CastPart {{ entity: {}, modality: {}, can_answer: {}, quote: {} }}",
        string(&part.entity),
        modality(part.modality),
        part.can_answer,
        string(&part.quote),
    )
}

fn fork(part: &ForkPart) -> String {
    format!(
        "::mnemosyne_engine::ForkPart {{ at: {}, parent: {}, world: {}, label: {} }}",
        string(&part.at),
        string(&part.parent),
        string(&part.world),
        string(&part.label),
    )
}

fn door(part: &DoorPart) -> String {
    match part {
        DoorPart::Fork { world, label } => format!(
            "::mnemosyne_engine::DoorPart::Fork {{ world: {}, label: {} }}",
            string(world),
            string(label)
        ),
        DoorPart::Examine { object, reveals } => format!(
            "::mnemosyne_engine::DoorPart::Examine {{ object: {}, reveals: {} }}",
            string(object),
            strings(reveals)
        ),
        DoorPart::Ask { question, reveals } => format!(
            "::mnemosyne_engine::DoorPart::Ask {{ question: {}, reveals: {} }}",
            string(question),
            string(reveals)
        ),
    }
}

fn interactivity(layer: &Interactivity) -> String {
    let mut ladders: Vec<(&String, &Vec<Rung>)> = layer.ladders.iter().collect();
    ladders.sort_by(|a, b| a.0.cmp(b.0));
    let mut objects: Vec<&String> = layer.objects.iter().collect();
    objects.sort();
    format!(
        "::mnemosyne_engine::Interactivity {{ ladders: {}.into_iter().collect(), \
         objects: {}.into_iter().collect(), free_investigate: {} }}",
        vec_of(&ladders, |(section, rungs)| format!(
            "({}, {})",
            string(section),
            vec_of(rungs, rung)
        )),
        vec_of(&objects, |id| string(id)),
        layer.free_investigate,
    )
}

fn rung(r: &Rung) -> String {
    format!(
        "::mnemosyne_engine::Rung {{ question: {}, question_anchor: {}, reveals: {}, needs: {} }}",
        string(&r.question),
        option(r.question_anchor.as_ref().map(anchor)),
        string(&r.reveals),
        strings(&r.needs),
    )
}

fn anchor(a: &ContentAnchor) -> String {
    let locator = match &a.locator {
        Locator::Prefix(p) => format!("::mnemosyne_engine::Locator::Prefix({})", string(p)),
        Locator::Cfi(c) => format!("::mnemosyne_engine::Locator::Cfi({})", string(c)),
    };
    format!(
        "::mnemosyne_engine::ContentAnchor {{ source: {}, locator: {locator} }}",
        string(&a.source)
    )
}

fn disclosure_mode(mode: mnemosyne_engine::DisclosureMode) -> String {
    let variant = match mode {
        mnemosyne_engine::DisclosureMode::Withhold => "Withhold",
        mnemosyne_engine::DisclosureMode::State => "State",
        mnemosyne_engine::DisclosureMode::Hint => "Hint",
        mnemosyne_engine::DisclosureMode::Imply => "Imply",
    };
    format!("::mnemosyne_engine::DisclosureMode::{variant}")
}

fn modality(modality: mnemosyne_engine::Modality) -> String {
    let variant = match modality {
        mnemosyne_engine::Modality::Observed => "Observed",
        mnemosyne_engine::Modality::Guessed => "Guessed",
        mnemosyne_engine::Modality::Told => "Told",
        mnemosyne_engine::Modality::Remembered => "Remembered",
    };
    format!("::mnemosyne_engine::Modality::{variant}")
}
