// The code generator: ProjectionParts -> Rust source (Round 770).
//
// `include!`d by this crate's own `build.rs` as well as compiled into the lib,
// so the generator that CI compiles is the same text the build script runs —
// there is no second copy to drift. That is also why this file carries `//`
// comments rather than `//!` module docs: an inner doc comment cannot appear
// where an `include!` splices it.

use std::borrow::Cow;
use std::fmt::Write as _;
use std::num::NonZeroUsize;

use mnemosyne_engine::{
    CastPart, ContentAnchor, DoorPart, ForkPart, Interactivity, LinePart, Locator, PassagesParts,
    ProjectionParts, QuestCompletionPart, QuestPart, QuestProjectionParts, QuestWorldPart, Rung,
};

/// The item the generated playable source defines, and the type it returns.
const FN_NAME: &str = "playable_projection";
const PLAYABLE_PROJECTION_TY: &str = "::mnemosyne_engine::PlayableProjection";

/// The item the generated quest source defines, and the type it returns (Round 774).
const QUEST_FN_NAME: &str = "quest_projection";
const QUEST_PROJECTION_TY: &str = "::mnemosyne_engine::QuestProjection";

/// The item the generated passage source defines, and the type it returns
/// (Round 791). A map rather than a kernel struct, because that is what
/// `store_passages` returns and the bake replaces that call, not a type.
const PASSAGES_FN_NAME: &str = "passages";
const PASSAGES_TY: &str =
    "::std::collections::HashMap<::std::string::String, ::mnemosyne_engine::Passage>";

/// The banner both generated files carry.
fn header(out: &mut String) {
    out.push_str("// @generated by mnemosyne-engine-build. Do not edit.\n");
    out.push_str("// Baked from the store at build time; regenerated whenever the store moves.\n");
}

/// Assemble one whole artifact: `chunks`' functions walled off in a private
/// module, `build` as that module's entry point, and the public item delegating
/// into it.
///
/// Both emitters end here rather than each writing its own tail, so the
/// composition rule below cannot hold on one axis and quietly not on the other —
/// the seam Round 779 closed for doors, in the place Round 774 opened a second
/// emitter.
///
/// # Why the chunk functions get a module
///
/// [`chunked`] names them `__mn_0`, `__mn_1`, … from a counter that restarts at
/// zero for every render, so two artifacts define the SAME private names.
/// Splicing both into one module — the composition this crate's own docs
/// describe — is then `E0428` once per chunk, and the first consumer met exactly
/// that on wiring the quest axis up beside the playable one.
///
/// A module rather than the per-emitter name prefix the consumer suggested, and
/// the reason is Round 777's: a prefix is a constant picked per emitter, which is
/// a hand list a third emitter can silently fail to extend, and a name merely
/// absent looks the same as a name deliberately shared. This one is DERIVED from
/// the public item the artifact defines, and two artifacts must already define
/// different public items to compose at all — so the wall is distinct exactly
/// when composition is possible, for an emitter nobody has written yet.
///
/// It is also the cheaper of the two on the axis Round 775 gates, though by less
/// than it first appears and the measurement is worth keeping honest. A prefix
/// lengthens every chunk name, at its definition and again at its reference in
/// the reassembly expression, and both counts grow with the store. The module is
/// three lines and 128 bytes for the whole artifact however large the store gets.
/// Measured on the 800-line stack fixture, neither moves the LONGEST line: that
/// is a chunk body at 15,120 bytes against a reassembly of 332.
///
/// # Why the public item hands back a borrow (Round 786)
///
/// It returns `&'static {ty}` from a `OnceLock` rather than the projection by
/// value, and that one change is what lets a consumer stop copying. Lifetime
/// elision writes `pub fn text(&self) -> &str` as `fn text<'s>(&'s self) -> &'s
/// str`, so a projection borrowed for the process yields `&'static str` from
/// accessors nobody touched. The first consumer transforms 4,612 lines into its
/// own type today for one reason: the projection was a VALUE it had to own, its
/// struct held that value, and borrowing out of it would have been
/// self-referential. Handing back a `&'static` removes the reason rather than
/// widening the API.
///
/// `OnceLock` rather than a true `static` because a `static` needs const
/// construction, which admits no `HashMap`, `Vec` or `String` — and this
/// projection is five maps and a set. The init runs `build` on the CALLING
/// thread, so the Round 780 stack gate still weighs the same frame.
///
/// `CELL` sits inside the function body, which is the scope that keeps Round
/// 781's composition rule intact: two artifacts spliced into one module define
/// two same-named statics, and a body-scoped `static` is private to its own
/// function. The wall above walls the chunk functions; this one needs no wall
/// because it was never in shared scope.
///
/// # It looks like a leak to a heap profiler, and is not (Round 788)
///
/// The projection lives in a `OnceLock` for the life of the process, so it is
/// never dropped and its allocations are never freed. A consumer measuring
/// startup with valgrind sees allocs and frees diverge sharply — the first one
/// measured 35,559 frees before this change and 104 after, with `in use at exit`
/// reporting the whole projection, 2.8 MB. That is the intended shape of a
/// process-lifetime value rather than a lost pointer: it is reachable from the
/// `OnceLock` at exit, so it is "still reachable", not "definitely lost". They
/// knew why and were not alarmed; a consumer who does not would read it as a
/// regression this crate introduced.
fn artifact(fn_name: &str, ty: &str, chunks: &Chunks, build: &str) -> String {
    let module = format!("__mn_{fn_name}");
    let mut out = String::new();
    header(&mut out);
    let _ = writeln!(out, "mod {module} {{");
    out.push_str(&chunks.fns);
    let _ = writeln!(out, "pub fn build() -> {ty} {{");
    out.push_str(build);
    out.push_str("}\n}\n");
    let _ = writeln!(out, "pub fn {fn_name}() -> &'static {ty} {{");
    let _ = writeln!(
        out,
        "static CELL: ::std::sync::OnceLock<{ty}> = ::std::sync::OnceLock::new();"
    );
    let _ = writeln!(out, "CELL.get_or_init({module}::build)");
    out.push_str("}\n");
    out
}

/// How many literals one generated function may hold (Round 775).
///
/// The number that matters is not this one but the fact that a bound EXISTS:
/// rustc's per-body work is superlinear, so an emitter that puts a whole store in
/// one function body pays worse than proportionally as the store grows. Measured
/// on a controlled pair — the same literals, the same types, the same bytes, in
/// one body versus many — 5,000 element literals took 29.1s and 1.21GB in one
/// body and 5.5s and 0.57GB in 100 bodies; halving the input to 2,500 took the
/// one-body case to 9.0s, so doubling the input cost 3.2x the time. 50 is the
/// chunk that measurement used. Anything that keeps bodies small works; nothing
/// that leaves one body unbounded does.
const CHUNK: NonZeroUsize = NonZeroUsize::new(50).unwrap();

/// The environment variable that moves the gate fixtures to a consumer's own
/// scale (Round 788), naming the LARGER of the pair.
///
/// `dead_code` is allowed on this and the two items below for one reason, and it
/// is the same reason this file exists: `build.rs` `include!`s it, so the caller
/// is real but invisible to the lib build. Removing the allow would mean moving
/// the logic into the build script, which is exactly the second copy the header
/// of this file refuses.
#[allow(dead_code)]
pub(crate) const FIXTURE_LINES_ENV: &str = "MN_FIXTURE_LINES";

/// The default larger fixture size — the one Round 780 and Round 782 measured at.
#[allow(dead_code)]
const DEFAULT_BIG: usize = 800;

/// Resolve the `(small, big)` fixture pair from an optional override.
///
/// # Why an override exists (Round 788)
///
/// Round 782 measured the allocation and compile arms at 800 lines, and Round 785
/// carried forward that the first consumer's store is roughly forty times that
/// with the ratios at that scale unmeasured. That consumer then reported it CANNOT
/// answer the question: the sizes were `const`s in this crate's build script, so
/// running the fixtures at its own scale meant editing somebody else's repository.
/// The measurement it offered to run is the only real answer to the carry, so the
/// knob is the cheaper half of it.
///
/// # Why ONE number, and why it names the big end
///
/// The pair is not two independent sizes. Every assertion built on it says some
/// cost is the SAME at both, which is a claim only a fixed multiple can make, so
/// a consumer able to set them apart could produce a pair that reads green while
/// asserting nothing. `small` is DERIVED, and the 4:1 ratio every doc in this
/// crate states stays true by construction rather than by agreement.
///
/// It names the big end because that is the size the arms are compared AT — the
/// 5.5x compile figure is owned against borrowed at `big`, so a consumer matching
/// its store size matches it there.
///
/// # Errors
///
/// A `String` naming the problem, for a build script to panic with: unparseable,
/// zero, or not divisible by four. The last is refused rather than truncated —
/// a `big` of 4,610 would silently give a 3.998:1 pair while every doc here says
/// four times, which is the drift this crate exists downstream to catch.
#[allow(dead_code)]
pub(crate) fn fixture_sizes(override_raw: Option<&str>) -> Result<(usize, usize), String> {
    let big = match override_raw {
        None => DEFAULT_BIG,
        Some(raw) => raw
            .trim()
            .parse::<usize>()
            .map_err(|e| format!("{FIXTURE_LINES_ENV}={raw:?} is not a line count: {e}"))?,
    };
    if big == 0 {
        return Err(format!("{FIXTURE_LINES_ENV}=0 has no pair to compare"));
    }
    if big % 4 != 0 {
        return Err(format!(
            "{FIXTURE_LINES_ENV}={big} is not divisible by 4, and the gates assert \
             a cost is unchanged at FOUR times the store — pick {} or {}",
            big - (big % 4),
            big + (4 - big % 4)
        ));
    }
    Ok((big / 4, big))
}

/// The chunk functions emitted so far, the counter that keeps their names
/// unique, and the bound they obey. Threaded through the renderers because a
/// list at ANY depth may be the one that grows.
struct Chunks {
    fns: String,
    next: usize,
    /// Literals per generated function. A field rather than a read of [`CHUNK`]
    /// so the bound is a value this crate's own gate can SET: the stack gate
    /// compiles a deliberately unbounded control beside the bounded artifact and
    /// asserts the two behave differently, which is a claim no test can make
    /// while the bound is welded to one number. `NonZeroUsize` because
    /// `slice::chunks(0)` panics — a zero bound is unrepresentable rather than a
    /// runtime surprise.
    bound: NonZeroUsize,
}

impl Chunks {
    fn new() -> Self {
        Self::bounded(CHUNK)
    }

    fn bounded(bound: NonZeroUsize) -> Self {
        Self {
            fns: String::new(),
            next: 0,
            bound,
        }
    }
}

/// Emit `items` as chunk FUNCTIONS of at most [`CHUNK`] literals each and return
/// the expression that reassembles them, instead of returning one `vec![..]`
/// literal (Round 775).
///
/// `ty` is the element type as generated Rust — the thing that keeps this a typed
/// bake rather than a table of strings. It is written out rather than inferred
/// because a function signature cannot infer, and getting it wrong is a build
/// failure in this crate's own fixture, not a silent one downstream.
///
/// `each` takes the emitter too, so a nested list chunks itself: the bound holds
/// at every depth, not only at the top.
fn chunked<T>(
    chunks: &mut Chunks,
    ty: &str,
    items: &[T],
    each: impl Fn(&mut Chunks, &T) -> String,
) -> String {
    if items.is_empty() {
        return "::std::vec::Vec::new()".to_string();
    }
    let mut bodies: Vec<String> = Vec::with_capacity(items.len());
    for item in items {
        bodies.push(each(chunks, item));
    }
    let mut names: Vec<String> = Vec::new();
    let bound = chunks.bound.get();
    for group in bodies.chunks(bound) {
        let name = format!("__mn_{}", chunks.next);
        chunks.next += 1;
        let _ = writeln!(
            chunks.fns,
            "fn {name}() -> ::std::vec::Vec<{ty}> {{ vec![{}] }}",
            group.join(", ")
        );
        names.push(name);
    }
    let (first, rest) = names.split_first().expect("a non-empty item list chunks");
    if rest.is_empty() {
        return format!("{first}()");
    }
    let extends: String = rest
        .iter()
        .map(|name| format!(" v.extend({name}());"))
        .collect();
    format!("{{ let mut v = {first}();{extends} v }}")
}

/// The element types the generated chunk functions declare. Named rather than
/// inlined so the nested ones stay readable — a `by_world` element is a world
/// paired with its sections paired with their lines.
const STRING_TY: &str = "::std::string::String";
const LINE_TY: &str = "::mnemosyne_engine::LinePart";
const SECTION_LINES_TY: &str =
    "(::std::string::String, ::std::vec::Vec<::mnemosyne_engine::LinePart>)";
/// Spelled with the kernel's own [`SectionLines`](mnemosyne_engine::SectionLines)
/// alias rather than expanded. Not cosmetic: expanded, this is four levels of
/// nesting and `clippy::type_complexity` REJECTS it — in the generated file, in a
/// consumer's build, under the `-D warnings` a consumer is entitled to run. A
/// generator whose output does not survive its consumer's lints has not finished
/// generating.
const WORLD_TY: &str = "(::std::string::String, ::mnemosyne_engine::SectionLines)";
const WALK_TY: &str = "(::std::string::String, ::std::vec::Vec<::std::string::String>)";
/// `world -> (section -> the journal-routed fact ids there)` (Round 787). Named
/// through the kernel's alias for the same reason `SectionLines` is: the emitted
/// chunk signature is the parts type spelled out, and two spellings of one type
/// is the drift this crate exists downstream to catch.
const WORLD_OFFERS_TY: &str = "(::std::string::String, ::mnemosyne_engine::SectionJournalOffers)";
const TITLE_TY: &str = "(::std::string::String, ::std::string::String)";
const CAST_TY: &str = "::mnemosyne_engine::CastPart";
const SECTION_CAST_TY: &str =
    "(::std::string::String, ::std::vec::Vec<::mnemosyne_engine::CastPart>)";
const FORK_TY: &str = "::mnemosyne_engine::ForkPart";
const CHOICE_REF_TY: &str = "::mnemosyne_engine::ChoiceEntityRef";
const DOOR_TY: &str = "::mnemosyne_engine::DoorPart";
const SECTION_DOORS_TY: &str =
    "(::std::string::String, ::std::vec::Vec<::mnemosyne_engine::DoorPart>)";
const RUNG_TY: &str = "::mnemosyne_engine::Rung";
const SECTION_RUNGS_TY: &str = "(::std::string::String, ::std::vec::Vec<::mnemosyne_engine::Rung>)";
const QUEST_TY: &str = "::mnemosyne_engine::QuestPart";
const QUEST_WORLD_TY: &str = "(::std::string::String, ::mnemosyne_engine::QuestWorldPart)";
const QUEST_COMPLETION_TY: &str = "::mnemosyne_engine::QuestCompletionPart";

/// Render parts as Rust source. Deterministic — [`ProjectionParts`] is emitted in
/// sorted key order (R769), so an unchanged store yields a byte-identical file
/// and a no-op rebuild churns nothing downstream.
///
/// Every list becomes [`chunked`] functions rather than one literal (R775), so no
/// function body grows with the store. The one body that still scales with the
/// world is the [`artifact`] module's `build`, and it holds one CALL per chunk —
/// the structure, never the prose.
#[must_use]
pub fn render(parts: &ProjectionParts) -> String {
    render_bounded(parts, CHUNK)
}

/// [`render`] at a CALLER-CHOSEN bound — the seam this crate's stack gate needs
/// and the only reason the bound is a value rather than a constant read.
///
/// The gate compiles the same parts twice, once at [`CHUNK`] and once unbounded,
/// and asserts the bounded artifact builds inside a small stack while the
/// unbounded one does not. Without a way to EMIT the unbounded shape, that second
/// half could only ever be a comment claiming someone checked once — and a gate
/// that cannot demonstrate it discriminates is the shape Rounds 776-779 spent
/// four rounds removing. Deliberately not `pub`: a consumer has no business
/// choosing a bound, and the one caller that does lives in this crate.
pub(crate) fn render_bounded(parts: &ProjectionParts, bound: NonZeroUsize) -> String {
    let mut c = Chunks::bounded(bound);
    let by_world = chunked(&mut c, WORLD_TY, &parts.by_world, |c, (world, sections)| {
        let sections = chunked(c, SECTION_LINES_TY, sections, |c, (section, lines)| {
            let lines = chunked(c, LINE_TY, lines, |_, l| line(l));
            format!("({}, {})", string(section), lines)
        });
        format!("({}, {})", string(world), sections)
    });
    let walks = chunked(&mut c, WALK_TY, &parts.walks, |c, (world, walk)| {
        format!("({}, {})", string(world), strings(c, walk))
    });
    let titles = chunked(&mut c, TITLE_TY, &parts.titles, |_, (section, title)| {
        format!("({}, {})", string(section), string(title))
    });
    let cast = chunked(
        &mut c,
        SECTION_CAST_TY,
        &parts.cast,
        |c, (section, members)| {
            let members = chunked(c, CAST_TY, members, |_, m| cast(m));
            format!("({}, {})", string(section), members)
        },
    );
    let forks = chunked(&mut c, FORK_TY, &parts.forks, |_, f| fork(f));
    let divergent_endings = strings(&mut c, &parts.divergent_endings);
    let interactivity = interactivity(&mut c, &parts.interactivity);
    let choice_entity_refs = chunked(&mut c, CHOICE_REF_TY, &parts.choice_entity_refs, |_, r| {
        format!(
            "::mnemosyne_engine::ChoiceEntityRef {{ section: {}, entity: {}, choice: {} }}",
            string(&r.section),
            string(&r.entity),
            string(&r.choice)
        )
    });
    let ask_doors = chunked(
        &mut c,
        SECTION_DOORS_TY,
        &parts.ask_doors,
        |c, (section, doors)| {
            let doors = chunked(c, DOOR_TY, doors, |_, d| door(d));
            format!("({}, {})", string(section), doors)
        },
    );
    let journal_offers = chunked(
        &mut c,
        WORLD_OFFERS_TY,
        &parts.journal_offers,
        |c, (world, sections)| {
            let sections = chunked(c, WALK_TY, sections, |c, (section, ids)| {
                format!("({}, {})", string(section), strings(c, ids))
            });
            format!("({}, {})", string(world), sections)
        },
    );

    let mut build = String::new();
    build.push_str("    ::mnemosyne_engine::PlayableProjection::from_parts(\n");
    build.push_str("        ::mnemosyne_engine::ProjectionParts {\n");
    let _ = writeln!(build, "            telling: {},", string(&parts.telling));
    let _ = writeln!(build, "            by_world: {by_world},");
    let _ = writeln!(build, "            walks: {walks},");
    let _ = writeln!(build, "            titles: {titles},");
    let _ = writeln!(build, "            cast: {cast},");
    let _ = writeln!(build, "            forks: {forks},");
    let _ = writeln!(build, "            divergent_endings: {divergent_endings},");
    let _ = writeln!(build, "            interactivity: {interactivity},");
    let _ = writeln!(
        build,
        "            choice_entity_refs: {choice_entity_refs},"
    );
    let _ = writeln!(build, "            ask_doors: {ask_doors},");
    let _ = writeln!(build, "            journal_offers: {journal_offers},");
    build.push_str("        },\n    )\n");
    artifact(FN_NAME, PLAYABLE_PROJECTION_TY, &c, &build)
}

/// Render quest parts as Rust source (Round 774) — the JOURNAL-axis sibling of
/// [`render`], emitting `pub fn quest_projection() -> &'static QuestProjection`.
///
/// Deterministic for a reason worth keeping separate from the playable one:
/// [`QuestProjectionParts`] is already ordered at its source (a `BTreeSet`-derived
/// quest list, a `BTreeMap` per world, preconditions sorted at ingestion), so
/// nothing is sorted on the way out here either.
#[must_use]
pub fn render_quest(parts: &QuestProjectionParts) -> String {
    let mut c = Chunks::new();
    let quests = chunked(&mut c, QUEST_TY, &parts.quests, quest);
    let mut build = String::new();
    build.push_str("    ::mnemosyne_engine::QuestProjection::from_parts(\n");
    build.push_str("        ::mnemosyne_engine::QuestProjectionParts {\n");
    let _ = writeln!(build, "            telling: {},", string(&parts.telling));
    let _ = writeln!(build, "            quests: {quests},");
    build.push_str("        },\n    )\n");
    artifact(QUEST_FN_NAME, QUEST_PROJECTION_TY, &c, &build)
}

fn quest(chunks: &mut Chunks, part: &QuestPart) -> String {
    let per_world = chunked(
        chunks,
        QUEST_WORLD_TY,
        &part.per_world,
        |chunks, (world, state)| format!("({}, {})", string(world), quest_world(chunks, state)),
    );
    format!(
        "::mnemosyne_engine::QuestPart {{ quest_id: {}, objective: {}, actors: {}, \
         prerequisites: {}, per_world: {per_world}, preconditions: {} }}",
        string(&part.quest_id),
        string(&part.objective),
        inline_strings(&part.actors),
        inline_strings(&part.prerequisites),
        inline_strings(&part.preconditions),
    )
}

fn quest_world(chunks: &mut Chunks, part: &QuestWorldPart) -> String {
    format!(
        "::mnemosyne_engine::QuestWorldPart {{ state: {}, completions: {} }}",
        quest_state(part.state),
        chunked(chunks, QUEST_COMPLETION_TY, &part.completions, |_, c| {
            quest_completion(c)
        }),
    )
}

fn quest_completion(part: &QuestCompletionPart) -> String {
    format!(
        "::mnemosyne_engine::QuestCompletionPart {{ fact: {}, scene: {}, actor: {} }}",
        string(&part.fact),
        string(&part.scene),
        option(part.actor.as_deref().map(string)),
    )
}

fn quest_state(state: mnemosyne_engine::QuestState) -> String {
    let variant = match state {
        mnemosyne_engine::QuestState::Done => "Done",
        mnemosyne_engine::QuestState::Open => "Open",
        mnemosyne_engine::QuestState::Unknown => "Unknown",
    };
    format!("::mnemosyne_engine::QuestState::{variant}")
}

/// A Rust string literal for `s`. `{:?}` on a `&str` is exactly the escaping
/// rules of a Rust literal, so this is a correct quoter rather than an
/// approximate one — a claim worth stating because the values being quoted are
/// authored prose full of quotes, newlines and non-ASCII.
fn string(s: &str) -> String {
    format!("{s:?}.to_string()")
}

/// The same escaping WITHOUT the `.to_string()` — a bare `&'static str` literal
/// (Round 793), for a field that borrows rather than owns.
///
/// It is a separate function rather than a flag on [`string`] because the two
/// produce different TYPES, and a boolean deciding a type at a call site is the
/// thing that reads correct while being wrong.
///
/// This carried a second claim, that dropping `.to_string()` is also most of the
/// 5.5x compile gap Round 782 measured between an owned and a borrowed artifact.
/// Round 794 separated the causes with arms that vary one at a time, and it is
/// the smaller half by a wide margin: removing four `.to_string()`s per line
/// moved rustc from 0.46s to 0.43s, while removing the one `vec![..]` beside them
/// moved it from 0.43s to 0.20s. What rustc charges for is the per-line
/// CONSTRUCTOR CALL, and `.to_string()` was the most visible instance rather than
/// the expensive one. This function still writes the cheaper literal and still
/// removes an allocation per field; what it does not do is buy the compile time
/// the sentence it replaces promised.
fn str_literal(s: &str) -> String {
    format!("{s:?}")
}

fn strings(chunks: &mut Chunks, items: &[String]) -> String {
    chunked(chunks, STRING_TY, items, |_, s| string(s))
}

fn option(inner: Option<String>) -> String {
    inner.map_or_else(|| "None".to_string(), |value| format!("Some({value})"))
}

/// A line's own string lists are emitted INLINE rather than chunked: a line names
/// a handful of entities, and a chunk function per line would cost more items
/// than it bounds. The bound that matters is on the list OF lines, which
/// [`render`] chunks.
fn inline_strings(items: &[String]) -> String {
    if items.is_empty() {
        return "::std::vec::Vec::new()".to_string();
    }
    let body: Vec<String> = items.iter().map(|s| string(s)).collect();
    format!("vec![{}]", body.join(", "))
}

/// A `Cow::Borrowed` of the literal — what a baked field carries so the line
/// POINTS at the binary instead of copying it (Round 795).
fn cow(s: &str) -> String {
    format!("::std::borrow::Cow::Borrowed({})", str_literal(s))
}

/// A line's entity list as a BORROWED slice of borrowed strings.
///
/// The slice is written inline rather than through a named `static`, relying on
/// rvalue static promotion — checked by compilation in Round 794, together with
/// the discriminating half (the same shape holding a runtime `String` fails
/// `E0515`), because a named `static` per line would add an ITEM per line and
/// Round 789 measured that rustc charges per item.
///
/// Borrowing the list and not only its strings is what Round 794 measured as the
/// difference between 80% and 100% of the allocation win: a `Vec` spine costs one
/// allocation per line whatever the strings do.
fn inline_cow_strings(items: &[Cow<'static, str>]) -> String {
    if items.is_empty() {
        return "::std::borrow::Cow::Borrowed(&[])".to_string();
    }
    let body: Vec<String> = items.iter().map(|s| cow(s)).collect();
    format!("::std::borrow::Cow::Borrowed(&[{}])", body.join(", "))
}

fn line(part: &LinePart) -> String {
    format!(
        "::mnemosyne_engine::LinePart {{ fact_id: {}, text: {}, mode: {}, frame: {}, \
         entities: {}, carrier: {}, typed_predicate: {}, quote: {}, count: {} }}",
        cow(&part.fact_id),
        cow(&part.text),
        disclosure_mode(part.mode),
        cow(&part.frame),
        inline_cow_strings(&part.entities),
        option(part.carrier.as_deref().map(cow)),
        option(part.typed_predicate.as_deref().map(cow)),
        option(part.quote.as_deref().map(cow)),
        option(part.count.map(|c| format!("{c}i64"))),
    )
}

fn cast(part: &CastPart) -> String {
    format!(
        "::mnemosyne_engine::CastPart {{ entity: {}, modality: {}, can_answer: {}, quote: {} }}",
        string(&part.entity),
        modality(part.modality),
        part.can_answer,
        string(&part.quote),
    )
}

fn fork(part: &ForkPart) -> String {
    format!(
        "::mnemosyne_engine::ForkPart {{ at: {}, parent: {}, world: {}, label: {} }}",
        string(&part.at),
        string(&part.parent),
        string(&part.world),
        string(&part.label),
    )
}

fn door(part: &DoorPart) -> String {
    match part {
        DoorPart::Fork { world, label } => format!(
            "::mnemosyne_engine::DoorPart::Fork {{ world: {}, label: {} }}",
            string(world),
            string(label)
        ),
        DoorPart::Examine { object, reveals } => format!(
            "::mnemosyne_engine::DoorPart::Examine {{ object: {}, reveals: {} }}",
            string(object),
            inline_strings(reveals)
        ),
        DoorPart::Ask { question, reveals } => format!(
            "::mnemosyne_engine::DoorPart::Ask {{ question: {}, reveals: {} }}",
            string(question),
            string(reveals)
        ),
    }
}

fn interactivity(chunks: &mut Chunks, layer: &Interactivity) -> String {
    let mut ladders: Vec<(String, Vec<Rung>)> = layer
        .ladders
        .iter()
        .map(|(section, rungs)| (section.clone(), rungs.clone()))
        .collect();
    ladders.sort_by(|a, b| a.0.cmp(&b.0));
    let mut objects: Vec<String> = layer.objects.iter().cloned().collect();
    objects.sort();
    let ladders = chunked(
        chunks,
        SECTION_RUNGS_TY,
        &ladders,
        |chunks, (section, rungs)| {
            let rungs = chunked(chunks, RUNG_TY, rungs, |_, r| rung(r));
            format!("({}, {})", string(section), rungs)
        },
    );
    let objects = strings(chunks, &objects);
    format!(
        "::mnemosyne_engine::Interactivity {{ ladders: {ladders}.into_iter().collect(), \
         objects: {objects}.into_iter().collect(), free_investigate: {} }}",
        layer.free_investigate,
    )
}

fn rung(r: &Rung) -> String {
    format!(
        "::mnemosyne_engine::Rung {{ question: {}, question_anchor: {}, reveals: {}, needs: {} }}",
        string(&r.question),
        option(r.question_anchor.as_ref().map(anchor)),
        string(&r.reveals),
        inline_strings(&r.needs),
    )
}

/// Render a baked passage set as Rust source (Round 791) — the third emitter,
/// and the third to end in [`artifact`], so the composition rule and the
/// `&'static` handle hold on this axis without being re-derived.
///
/// Deterministic for the same reason the other two are: [`passages_to_parts`]
/// sorts by section id, so the same store emits byte-identical source.
///
/// # Why the passage set is chunked at all
///
/// Round 789 measured this axis before it was shaped, and found the opposite of
/// what both sides expected. Prose is FEW and LONG — 56 spots of ~2,655
/// characters in the first consumer's store — so the emitted longest line is
/// enormous (319 KB) and costs nothing: rustc charges per ITEM, and the whole
/// 1.43 MB artifact compiles in 0.05s against 2.47s for a line artifact of
/// nearly the same bytes in 4,612 items. [`CHUNK`] is therefore already the
/// right bound here, unchanged, and the Round 775 regression test passes because
/// it asserts a RATIO rather than a byte threshold. Nothing about this emitter
/// needed a special case; the measurement is what established that.
pub fn render_passages(parts: &PassagesParts) -> String {
    let mut c = Chunks::new();
    let entries = chunked(&mut c, PASSAGE_ENTRY_TY, &parts.passages, |_, (id, p)| {
        format!(
            "({}, ::mnemosyne_engine::PassagePart {{ anchor: {}, text: ::std::borrow::Cow::Borrowed({}) }})",
            string(id),
            anchor(&p.anchor),
            str_literal(&p.text)
        )
    });
    let mut build = String::new();
    build.push_str("    ::mnemosyne_engine::passages_from_parts(\n");
    build.push_str("        ::mnemosyne_engine::PassagesParts {\n");
    let _ = writeln!(build, "            passages: {entries},");
    build.push_str("        },\n    )\n");
    artifact(PASSAGES_FN_NAME, PASSAGES_TY, &c, &build)
}

/// One baked passage entry, as generated Rust.
const PASSAGE_ENTRY_TY: &str = "(::std::string::String, ::mnemosyne_engine::PassagePart)";

fn anchor(a: &ContentAnchor) -> String {
    let locator = match &a.locator {
        Locator::Prefix(p) => format!("::mnemosyne_engine::Locator::Prefix({})", string(p)),
        Locator::Cfi(c) => format!("::mnemosyne_engine::Locator::Cfi({})", string(c)),
    };
    format!(
        "::mnemosyne_engine::ContentAnchor {{ source: {}, locator: {locator} }}",
        string(&a.source)
    )
}

fn disclosure_mode(mode: mnemosyne_engine::DisclosureMode) -> String {
    let variant = match mode {
        mnemosyne_engine::DisclosureMode::Withhold => "Withhold",
        mnemosyne_engine::DisclosureMode::State => "State",
        mnemosyne_engine::DisclosureMode::Hint => "Hint",
        mnemosyne_engine::DisclosureMode::Imply => "Imply",
    };
    format!("::mnemosyne_engine::DisclosureMode::{variant}")
}

fn modality(modality: mnemosyne_engine::Modality) -> String {
    let variant = match modality {
        mnemosyne_engine::Modality::Observed => "Observed",
        mnemosyne_engine::Modality::Guessed => "Guessed",
        mnemosyne_engine::Modality::Told => "Told",
        mnemosyne_engine::Modality::Remembered => "Remembered",
    };
    format!("::mnemosyne_engine::Modality::{variant}")
}
